version: '3'
services:
  base-project-pg:
    container_name: book-store
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: book_store
    ports:
      - '5434:5432'